application: sachindra-project
version: 1
runtime: python27
threadsafe: True
api_version: 1


handlers:
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /.*
  script: library.application

